#ifndef GLOBAL_DEFINITIONS_H
#define GLOBAL_DEFINITIONS_H

enum vis_modes{VIS_LABELS = 0, VIS_SEGMENTATION, VIS_BONES_SEGMENTATION, VIS_WEIGHTS,VIS_SECW_ALONG, VIS_SECW_WIDE, VIS_ISODISTANCES, VIS_ISOLINES, VIS_POINTDISTANCES,VIS_ERROR,VIS_WEIGHT_INFLUENCE};

#endif // GLOBAL_DEFINITIONS_H
